import { IExperience } from '../component/experience/IExperience';

const experience: IExperience.Payload = {
  disable: false,
  disableTotalPeriod: false,
  list: [
    {
      title: '마이다스인',
      position: 'BACKEND DEVELOPER',
      startedAt: '2025-05',
      descriptions: [
        '<b>AI 역량검사 센터(ACCA) 백엔드 개발</b> - AI 기반 채용 평가 플랫폼의 LLM 런타임, AI 면접, NCS/공공 역검, 파일/엑셀 배치, 스케줄러, 멀티테넌트 DB 영역 담당',
        '<b>실무능력 LLM 런타임 구축</b>',
        '- 질문 계획, 답변 추적, 꼬리질문, Phase2 생성, 결과 outbox 발행 흐름을 설계하고 durable worker queue를 도입해 장시간 평가의 재시도/복구 가능성을 확보',
        '- MongoDB 기반 session, turn, event log, trace, transcript, runtime inbox/outbox 모델을 구성해 LLM runtime state를 durable하게 저장',
        '- Kafka DTO/topic, Redis lock/progress cache, 질문 출처 enum, TTS scene 분기 기준을 공통 계약으로 이동해 서비스 간 연동 경계를 정리',
        '<b>OpenAI STT/TTS 및 관측성 연동</b>',
        '- OpenAI native SDK 기반 realtime STT client secret, 파일 전사 API, TTS streaming/cache/voice option을 구현',
        '- Langfuse trace, prompt link, token/rate-limit metadata logging을 보강해 LLM 호출 비용과 장애 분석 근거를 남김',
        '<b>Spring AI 기반 평가 자동화 기능 개발</b>',
        '- GPT-5 + Spring AI ChatClient 기반 <b>면접 질문 자동 생성 시스템</b> 구축 → 설계 시간 <b>70% 단축</b>',
        '- <b>Spring AI Tool</b> 호출과 JSON Schema 기반 <b>Structured Output</b>으로 평가 기준 검증 및 LLM 응답 안정성 확보',
        '- CMS AI 면접 질문 생성기와 큐레이터 챗봇 API의 prompt, validation, chat history, 평가기준 매핑, 저장 구조 개선',
        '<b>NCS/공공 역검 및 결과표 데이터 개발</b>',
        '- ACC/NCS 통합 전형 필터, 설정 검증, 결과/코멘트/점수 변환, mental health fact, T-score 변환을 백엔드와 tenant/core DB 모델에 반영',
        '- LLM-friendly 결과표 텍스트화, section separator, 주목 역량 코드 노출로 결과표 소비 경로 개선',
        '- Apache POI 기반 엑셀 결과표 생성 및 출력용 블라인드 옵션으로 <b>공정채용 가이드라인 준수</b>',
        '<b>성능 개선 및 운영 안정화</b>',
        '- Querydsl 기반 조회 처리, Fetch Join + where in 일괄 조회, batch size 설정으로 <b>93% 쿼리 감소</b>',
        '- CMS 응시자 검색, 전형 설정 조회, manager context 조회에서 N+1/중복 조회를 줄여 운영 조회 성능 개선',
        '- SXSSFWorkbook, pagination, batch size, map-in 조회, SQL 기반 복사 흐름으로 대용량 엑셀 OOM 리스크 완화',
        '- 대량 안내 메일 스케줄러의 DB churn/latency를 줄이고 Querydsl Q-type startup warmup, S3/temp cleanup, 전형 삭제 FK 정리로 배치 안정성 개선',
      ],
      skillKeywords: [
        'Java 21',
        'Spring Boot 3.3',
        'Spring AI',
        'Langchain4j',
        'OpenAI GPT-5',
        'OpenAI STT/TTS',
        'JPA/Hibernate',
        'Querydsl',
        'MariaDB',
        'MongoDB',
        'Redis',
        'Kafka',
      ],
    },
    {
      title: '그릿스탠다드',
      position: 'BACKEND DEVELOPER',
      startedAt: '2023-04',
      endedAt: '2025-02',
      descriptions: [
        '<b>물류 플랫폼/ERP 백엔드 개발 및 인프라 운영</b>',
        '- 기존 메일 시스템의 <b>동시성 문제</b>와 <b>Elasticsearch/RDBMS 상태 동기화 문제</b> 해결',
        '- FastAPI 비동기 이벤트 루프의 Blocking I/O 병목을 제거해 서비스 중단성 지연 현상 해결',
        '- <b>Pod 리소스 최적화</b>로 노드당 낭비 CPU를 제거하고 <b>Idle CPU 0.1 Core 미만 유지</b>',
        '- <b>Java JVM 옵션 최적화</b>로 메모리 할당을 개선해 <b>파드당 500MB 메모리 추가 확보</b>',
        '- HostPort 기반 Deployment 설정을 개선해 노드당 Pod 1개만 배치되던 운영 제약 해결',
      ],
      skillKeywords: [
        'Java',
        'Spring',
        'JPA',
        'Querydsl',
        'Kubernetes',
        'MySQL',
        'AWS',
        'Python',
        'FastAPI',
      ],
    },
  ],
};

export default experience;
